### ISSUE TITLE
[FEATURE] 기본 dropdown 구현 하기

### ISSUE THREAD

**Issue by j2h30728** [wanted-pre-onboarding-team-9/pre-onboarding-10th-3-9#1]
### 🤸 Describe the required feature
기본 dropdown 구현 하기

### 🏊 Todo

- [ ] 디자인 가이드(Figma)를 참고해서 InputTodo의 디자인 수정 및을 새로 만들기.
- [ ] Input에 500ms로 debounce를 적용하기
- [ ] Dropdown에 추천된 아이템들이 처음에 10개가 나올 수 있도록 하기
